language: java

jdk:
  - oraclejdk8
  


addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de
      - oracle-java8-installer

script:
- export CLASSPATH=.:lib/*
- cd src/jUnitTests
- javac *.java
- cd ../algorithm
- javac *.java
- cd ../../testsrc/testJUnitTests
- java org.junit.runner.JUnitCore GuiTest.java 

#lesezeichen