language: java

jdk:
  - oraclejdk8
  


addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de
      - oracle-java8-installer

script:
- export CLASSPATH=$CLASSPATH:$PWD/lib
- cd src/jUnitTests
- javac *.java
- cd ../algorithm
- javac -cp Measurement.java


#lesezeichenexport CLASSPATH=.:lib/*