language: java

jdk:
  - oraclejdk8
  


addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de
      - oracle-java8-installer

script:
- export CLASSPATH=$CLASSPATH:$PWD/lib:$PWD/src
- javac src/jUnitTests *.java
- javac src/algorithm Measurement.java


#lesezeichenexport CLASSPATH=.:lib/*