language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de

script:
- cd src
- cd jUnitTests
- javac *.java

# safelist
branches:
  only:
  - master

