language: java

jdk:
  - openjdk8
  
addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de
     
script:
- export CLASSPATH=$PWD/lib/*:$PWD/src/:$PWD/testsrc/:$CLASSPATH:.
- cd src/mainMethod
- javac *.java
- cd ../algorithm
- javac *.java
- cd ../inputOutput
- javac *.java
- cd ../userinterface
- javac *.java


#lesezeichenexport CLASSPATH=.:lib/*  export CLASSPATH=$CLASSPATH:$PWD/lib:$PWD/src
# home: /home/travis  - oracle-java8-installer