language: java

jdk:
  - oraclejdk8
  


addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de
      - oracle-java8-installer

script:
- export CLASSPATH=./lib/commons-math3-3.6.1.jar
- cd src/jUnitTests
- javac *.java
- cd ../algorithm
- javac -cp "./lib/commons-math3-3.6.1.jar" Measurement.java


#lesezeichenexport CLASSPATH=.:lib/*