language: java

jdk:
  - oraclejdk8
  
# safelist
branches:
  only:
  - master

addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de

script:
- ls
- cd src/jUnitTests
- javac *.java
- export CLASSPATH= /C:/Program' 'Files/ECLIPSE.450/plugins/:junit.jar:hamcrest-core.jar:$CLASSPATH 
- java org.junit.runner.JUnitCore GuiTest.java

# lesezeichen zum weiter machen 