language: java

jdk:
  - oraclejdk8
  
# safelist
branches:
  only:
  - master

addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de

script:
- ls
- cd src/jUnitTests
- javac *.java
- javac -cp /usr/lib/jvm/junit4.jar GuiTest.java
- java -cp /usr/lib/jvm/junit4.jar:. org.junit.runner.JUnitCore GuiTest.java

# lesezeichen zum weiter machen 