language: java

jdk:
  - oraclejdk8
  


addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de
      - oracle-java8-installer

script:
- cd src/jUnitTests
- javac -cp ./lib/commons-math3-3.6.1.jar:. *.java
- cd ../algorithm
- javac -cp lib/commons-math3-3.6.1.jar:. *.java


#lesezeichenexport CLASSPATH=.:lib/*