language: java

jdk:
  - oraclejdk8
  


addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de
      - oracle-java8-installer

script:
- echo $PATH
- export CLASSPATH=$CLASSPATH:~/lib/*:$PWD/src/inputOutput/*
- cd src/jUnitTests
- javac *.java
- cd ../algorithm
- javac  -classpath "~/libs/*:~/src/inputOutput/*" Measurement.java


#lesezeichenexport CLASSPATH=.:lib/*  export CLASSPATH=$CLASSPATH:$PWD/lib:$PWD/src
# home: /home/travis