language: java

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-de  

script:
- cd src
- cd jUnitTests
- javac SuperTest.java
- javac mainMethode.java
- javac Gui.java