language: java

jdk:
  - oraclejdk8
  


addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de
      - oracle-java8-installer

script:
- cd src/jUnitTests
- java *.java
- cd ../algorithm
- javac -cp ".:lib/*" Measurement.java


#lesezeichenexport CLASSPATH=.:lib/*  export CLASSPATH=$CLASSPATH:$PWD/lib:$PWD/src