language: java

jdk:
  - oraclejdk8
  


addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de
      - oracle-java8-installer

script:
- ls
- cd src/jUnitTests
- javac *.java
- cd ../algorithm
- javac  -classpath "./libs/*:./src/inputOutput/*" Measurement.java


#lesezeichenexport CLASSPATH=.:lib/*  export CLASSPATH=$CLASSPATH:$PWD/lib:$PWD/src