language: java

jdk:
  - oraclejdk8
  


addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de
      - oracle-java8-installer

script:
- export CLASSPATH=$PWD/lib/*:$PWD/src/:.:$CLASSPATH
- cd src/mainMethod
- javac *.java
- java *.java
- cd ../algorithm
- javac *.java
- java *.java
- cd ../inputOutput
- javac *.java
- java *.java
- cd ../userinterface
- javac *.java
- java *.java


#lesezeichenexport CLASSPATH=.:lib/*  export CLASSPATH=$CLASSPATH:$PWD/lib:$PWD/src
# home: /home/travis