language: java

jdk:
  - oraclejdk8

# safelist
branches:
  only:
  - master

addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de

script:
- cd src
- cd jUnitTests
- javac *.java
- cd testsrc
- cd testJUnitTests
- javac *.java