language: java

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update
  
# safelist
branches:
  only:
  - master

addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de

script:
- cd src/jUnitTests
- javac *.java
- cd ../../testsrc/testJUnitTests
- javac *.java