language: java

jdk:
  - oraclejdk8
  


addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de
      - oracle-java8-installer

script:
- cd src/jUnitTests
- javac *.java
- cd ../algorithm
- javac -sourcepath .:/Gesamtprojekt/src/inputOutput Measurement.java


#lesezeichenexport CLASSPATH=.:lib/*