language: java

jdk:
  - oraclejdk8
  
addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de
      - oracle-java8-installer
script:
- export CLASSPATH=$PWD/lib/*:$PWD/src/:$PWD/testsrc/:$CLASSPATH:.
- cd src/mainMethod
- javac *.java
- cd ../algorithm
- javac *.java
- cd ../inputOutput
- javac *.java
- cd ../userinterface
- javac *.java
- cd ../../testsrc/testalgorithm
- javac *.java
- cd ../testInputOutput
- javac *.java
- cd ../testUserinterface
- javac *.java
- cd ../..
- java mainMethod.main
- java algorithm.AverageMeasurement
- java algorithm.BoxPlot
- java algorithm.DataManager

#lesezeichenexport CLASSPATH=.:lib/*  export CLASSPATH=$CLASSPATH:$PWD/lib:$PWD/src
# home: /home/travis  - oracle-java8-installer