language: java

jdk:
  - oraclejdk8
  
addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de
      - oracle-java8-installer
script:
- unset DISPLAY
- export CLASSPATH=$PWD/lib/*:$PWD/src/:$PWD/testsrc/:$CLASSPATH:.
- cd src/mainMethod
- javac *.java
- cd ../algorithm
- javac *.java
- cd ../inputOutput
- javac *.java
- cd ../userinterface
- javac *.java
- cd ../../testsrc/testalgorithm
- javac *.java
- cd ../testInputOutput
- javac *.java
- cd ../testUserinterface
- javac *.java
- cd ../..
- java mainMethod.main1
- java testalgorithm.AlgorithmTest
- java testalgorithm.AlgorithmTest2
- java testalgorithm.ProgramLogicTest
- java testInputOutput.CSV_File_is_Empty_Test

#lesezeichenexport CLASSPATH=.:lib/*  export CLASSPATH=$CLASSPATH:$PWD/lib:$PWD/src
# home: /home/travis  - oracle-java8-installer