language: java

jdk:
  - oraclejdk8
  


addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de
      - oracle-java8-installer

script:
- export CLASSPATH=$PWD/lib/*:$PWD/src/:$PWD/testsrc/:$CLASSPATH:.
- mkdir bin
- cd src/mainMethod
- javac -d bin *.java
#- java bin/*
- cd ../algorithm
- javac -d bin *.java
#- java *.java
- cd ../inputOutput
- javac -d bin *.java
#- java *.java
- cd ../userinterface
- javac -d bin *.java
#- java *.java


#lesezeichenexport CLASSPATH=.:lib/*  export CLASSPATH=$CLASSPATH:$PWD/lib:$PWD/src
# home: /home/travis